site_name: py_uds
site_url: https://chaitu-ycr.github.io/py_uds/
site_description: Python UDS package
site_author: chaitu-ycr

repo_name: chaitu-ycr/py_uds
repo_url: https://github.com/chaitu-ycr/py_uds.git
edit_uri: blob/main/docs/

nav:
- about: index.md
- reference: 999_reference.md

theme:
  name: readthedocs
  features:
  - toc.integrate

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
  - search
