site_name: py_uds_lib
site_url: https://chaitu-ycr.github.io/py_uds_lib/
site_description: Python UDS Library
site_author: chaitu-ycr

repo_name: chaitu-ycr/py_uds_lib
repo_url: https://github.com/chaitu-ycr/py_uds_lib.git
edit_uri: blob/main/docs/

nav:
- about: index.md
- reference: 999_reference.md

theme:
  name: readthedocs
  features:
  - toc.integrate

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          show_source: false
          merge_init_into_class: true
- search
